/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjectTeacher;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import projectTeacher.Login;

public class AppTest extends Application {

	@Override
	public void start(Stage primaryStage) throws Exception {
		Scene scene = new Scene(new Login());
		primaryStage.setScene(scene);
		primaryStage.show();
	}
	
	public static void main(String[] args) {
		launch(args);
	}
}
